export const ACTION_0_SYNC = 'ACTION_NAME0'
export const ACTION_1_ASYNC_START = 'ACTION_NAME1_START'
export const ACTION_1_ASYNC_OK = 'ACTION_NAME1_OK'
export const ACTION_1_ASYNC_FAILED = 'ACTION_NAME1_FAIL'
