export const ACTION_LOGIN_REQEST = 'ACTION_LOGIN_REQEST'
export const ACTION_LOGIN_OK = 'ACTION_LOGIN_OK'
export const ACTION_LOGIN_FAILED = 'ACTION_LOGIN_FAILED'
export const ACTION_LOGOUT = 'ACTION_LOGOUT'
